apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  PORT: "3000"
  DB_HOST: "mysql"
  DB_PORT: "3306"
  DB_USER: "root"
  DB_NAME: "procurement_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  NODE_ENV: "production"
  JWT_SECRET: "supersecretjwtkey123"
  JWT_EXPIRES_IN: "1d"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          # Replace 'procurement-system-app' with your actual Docker Hub image if pushing to cloud
          image: procurement-system-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
